theme: jekyll-theme-minimal

title: Liz Izhikevich
locale: en_US
logo: hike.jpeg

owner:
  name: Liz Izhikevich
  avatar: profile.jpeg
  bio: "Ph.D. Candidate @ Stanford"
  email: lizhikev@stanford.edu
  linkedin: lizizhikevich
  github: lizizhikevich
  google:
    analytics:
    verify:
    scholar: jO0eK0AAAAAJ
